# Generated by Django 3.2.4 on 2021-06-11 19:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.IntegerField(default=0)),
                ('loan_period', models.IntegerField(default=0)),
                ('loan_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Funded'), (2, 'Completed')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('type', models.IntegerField(choices=[(0, 'Borrower'), (1, 'Investor')])),
                ('sufficient_balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_interest_rate', models.IntegerField(default=0)),
                ('approved_offer', models.BooleanField(default=False)),
                ('FK_loan_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.loan_request')),
                ('FK_user_investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.user')),
            ],
        ),
        migrations.AddField(
            model_name='loan_request',
            name='FK_user_borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.user'),
        ),
        migrations.CreateModel(
            name='Loan_Installments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('installment_amount', models.IntegerField(default=0)),
                ('FK_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.loan_request')),
            ],
        ),
    ]
